:sparkles: Add Create New Files and Merge flags
slashsBin/styleguide-git-commit-message pull request #17
Opened 2017-05-19 00:52 UTC by limaneto

Thos are the ones I've beeing missing.

2017-05-19 21:41 UTC, slashsBin commented
📰  is now for "new files", do you like it too?
I agree with 🤝  for merges.

2017-05-20 21:10 UTC, limaneto commented
Yeah that's okay.

2017-05-21 16:12 UTC, slashsBin commented on README.md
> +| :page_facing_up: | `:page_facing_up:` | when **add new file** to the project |
📰  is for new files now

2017-05-21 16:12 UTC, slashsbin requested changes
so please remove 📄  to merge the pull request.

2017-05-24 05:17 UTC, merged